before_install:
  - gem install cocoapods -v '0.32.1'
  - brew update
  - brew upgrade xctool

language: objective-c

xcode_workspace: PAYFormBuilder.xcworkspace
xcode_scheme: Example
xcode_sdk: iphonesimulator