before_install:
  - gem install cocoapods
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

language: objective-c

xcode_workspace: PAYFormBuilder.xcworkspace
xcode_scheme: Example
xcode_sdk: iphonesimulator