before_install:
  - gem install cocoapods -v '0.32.1'
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

language: objective-c

xcode_workspace: PAYFormBuilder.xcworkspace
xcode_scheme: Example
xcode_sdk: iphonesimulator